title: Matthew's Blog
description: >-
  Thoughts, ideas, and projects by Matthew Fitch.
baseurl: ""
url: "https://mw-ff.com"
twitter_username: matthewfitch23
github_username: matthewfitch23
linkedin_username: matthewwffitch
email: hello@mw-ff.com

lang: en-GB
timezone: Europe/London

permalink: /:categories/:year/:month/:day/:title/

permalink: pretty

favicon: /assets/favicon.png

defaults:
  - scope:
      path: ""
    values:
      author: Matthew Fitch

feed:
  path: feed.xml

theme: jekyll-theme-low
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
